name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install CMake
        run: |
          brew install cmake

      - name: Build llama.xcframework
        run: |
          chmod +x scripts/build_xcframework.sh
          MINIMAL_MODE=ios ./scripts/build_xcframework.sh

      - name: Build iOS App
        run: |
          xcodebuild \
            -project MiniCPM-V-demo/MiniCPM-V-demo.xcodeproj \
            -scheme MiniCPM-V-demo \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            archive \
            -archivePath "$PWD/build/MiniCPM-V-demo.xcarchive"

      - name: Create unsigned IPA
        run: |
          mkdir -p build/Payload

          cp -R \
            "build/MiniCPM-V-demo.xcarchive/Products/Applications/MiniCPM-V-demo.app" \
            "build/Payload/"

          cd build
          zip -r MiniCPM-V-demo-unsigned.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: VoxCPM2-iOS-IPA
          path: build/MiniCPM-V-demo-unsigned.ipa
